config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/edit'

  get 'articles/index'

  get 'articles/new'

  get 'articles/edit'

  get 'comments/index'

    get 'comments/new'

    get 'comments/edit'

    root :to => "posts#index"

resources :comments
    resources :articles

 get "sign_up" => "users#new", :as => "sign_up"
 resources :users
 resources :sessions
  resources :posts
  #root 'posts#index'
  
end

app/models/article.rb
class Article < ActiveRecord::Base

has_many :comments




default_scope {where(status: 'active')}

validates :title, presence: true,

                            length: { minimum: 5 }

        validates :content, presence: true,

                            length: { minimum: 10 }

        validates :status, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]


def download
    @articles = Article.all
    respond_to do |format| 
       format.xlsx {render xlsx: 'download',filename: "articles.xlsx"}
    end
end

  def index
  	@articles = Article.all
  end

  def new
  @article = Article.new
  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

   def destroy

    @article = Article.find_by_id(params[:id])

    if @article.destroy

        flash[:notice] = "Success Delete a Records"

        redirect_to action: 'index'

    else

        flash[:error] = "fails delete a records"

        redirect_to action: 'index'

    end

end

  def update

 @article = Article.find_by_id(params[:id])

 if @article.update(params_article)

    flash[:notice] = "Success Update Records"

    redirect_to action: 'index'

 else

    flash[:error] = "data not valid"

    render 'edit'

 end

end

 def show

        @article = Article.find_by_id(params[:id])

        @comments = @article.comments.order("id desc")

        @comment = Comment.new

    end

  def create
   @article = Article.new(params_article)

    if @article.save

        flash[:notice] = "Success Add Records"

        redirect_to action: 'index'

    else

        flash[:error] = "data not valid"

        render 'new'
    end
  end

  def export
  @article = Article.find_by_id(params[:id])
    @comments = @article.comments.all
    @comment = Comment.new
    filename = "article.xlsx"
    respond_to do|format|
      format.html
      format.xlsx{}
    end   

  def import
     spreadsheet = open_spreadsheet(file)
    page_article = spreadsheet.sheet('Article')

    (2..page_article.last_row).each do |no_row|
      @article = Article.create(
        title: page_article.row(no_row)[0],
        content: page_article.row(no_row)[1],
      status: page_article.row(no_row)[2])
    end

    page_comment = spreadsheet.sheet('Comment')
    (2..page_comment.last_row).each do |no_row|
      @comments = Comment.create(
        article_id: @article.id,
        user_is: page_comment.row(no_row)[1],
      content: page_comment.row(no_row)[2])
    end
  end

  end
   private

    def params_article

        params.require(:article).permit(:title, :content, :status)

    end




end

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>

        <p>

        <b><%= comment.user.try(:username) %></b>

        <br />

        <%= comment.content %>

        </p>

    <% end %>

app/views/articles/_form.html.erb
 <%= form_for @comment, url: comments_path, remote: true do |f| %>

        <%= f.hidden_field :article_id, value: @article.id %>

        <% if current_user %>

            <%= f.hidden_field :user_id, value: current_user.id %>

        <% end %>

        <br/>

        <%= f.label :content %>

        <%= f.text_area :content, cols: 20, rows: 10 %>

        <br/>

        <%= f.submit :submit %>

    <% end %>

app/views/articles/edit.html.erb
 <%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off" %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>


<div>

<%= link_to "back to index", articles_path %>

</div>

app/views/articles/index.html.erb
 <% @articles.each do |article| %>



<h3><%= article.title %></h3>

<p><%= article.content.truncate (20) %></p>

 <%= link_to 'read more', article_path(article.id) %>

<h4>status : <%= article.status %></h4>

 <p>

<span><%= link_to 'edit', edit_article_path(article.id) %><span>

 <span> | </span>

<span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data ? '} %><span>

</p>

<hr/>

 <h4>

<% if !current_user %>

<%= link_to 'Log-in', new_session_path %>

<% else %>

Hello <%= current_user.username %>

<%= link_to 'Log-Out', session_path(current_user.id), method: "DELETE" %>

<% end %>

</h4>

<% end %>

app/views/articles/index.xlsx.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Article">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">title</Data></Cell>
        <Cell><Data ss:Type="String">content</Data></Cell>
        <Cell><Data ss:Type="String">status</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String"><%= @article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @article.content %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @article.status %></Data></Cell>
      </Row>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Comment">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">article_id</Data></Cell>
        <Cell><Data ss:Type="String">user_id</Data></Cell>
        <Cell><Data ss:Type="String">content</Data></Cell>
      </Row>
    <% @article.comments.each do |comment| %>
      <Row> 
         <Cell><Data ss:Type="String"><%= comment.article_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.user_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.content %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/articles/new.html.erb
  <%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off", :checked => true %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>

    <p><%= @article.content %></p>

    <p><%= link_to 'back to index', articles_path %></p>


    <div id="form-comment">

        <%= render 'form' %>

    </div>


    <h4>Here the comments</h4>


    <div id="list-comments">

        <%= render 'comments' %>

    </div>