config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/edit'

  get 'articles/index'

  get 'articles/new'

  get 'articles/edit'

  get 'comments/index'

    get 'comments/new'

    get 'comments/edit'

    root :to => "posts#index"

resources :comments
    resources :articles

 get "sign_up" => "users#new", :as => "sign_up"
 resources :users
 resources :sessions
  resources :posts
  #root 'posts#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#", icon: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		redirect_to @post
  		else 
  		render 'new'
  		end	
  end

  def show 
  end

 def edit
  end

 def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end



  private
  
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body, :image)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>

<div class="form-group label-floating is-empty"> </div>
                <label for="555" class="control-label">People</label>
                <%= f.text_field :title,:class=>"form-control" %> <br>
 </div>

<div label class="control-label">About</label></div>
<div class="form-group label-floating is-empty">
<%= f.text_area :body, :class=>"form-control"%></div>

<div class="field"> 

	<%= f.label :image %><br>
	<%=f.file_field :image %>
</div>




	
	
	<br>
	<br>

         <div class="row">
          <%= f.submit :class=> "btn btn-raised btn-success ripple-container"  %>
    
        </div>
	
	<% end %>
	

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "main" %>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="<%= image_url('ridwankamil.jpg')%>" width="500" height="500" style="border:5px solid black">
      <div class="carousel-caption">
       
      </div>
    </div>

    <div class="item">
      <img src="<%= image_url('JoseMourinho.jpg')%>" width="500" height="500" style="border:5px solid black"> 
      <div class="carousel-caption">
       
      </div>
    </div>

    <div class="item">
      <img src="<%= image_url('billgates.jpg')%>" width="500" height="500" style="border:5px solid black">
      <div class="carousel-caption">
       
      </div>
    </div>
   
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<table>
<tbody>

<% @posts.each do |post| %>
	<tr>
	<td><h2><%= post.title%></h2></td>
	</tr>
	<tr>
	<td><%= image_tag post.image.url(:thumb)%></td>
	</tr>
	<tr>
	<td><%= link_to "Read Post", post %></td>
	</tr>
	
	<% end %>

</tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>

<head>
    <!-- Material Design fonts -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

  <!-- Bootstrap -->
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

  <!-- Bootstrap Material Design -->
  <link rel="stylesheet" type="text/css" href="bootstrap-material-design/dist/css/bootstrap-material-design.css">
  <link rel="stylesheet" type="text/css" href="bootstrap-material-design/dist/css/ripples.min.css">
    

</head>

<body>

<div class="row">
  <div class="col-md-3">
  	 <div class="row-picture">
        <img class="img-circle" src="<%= @post.image.url (:medium) %>">
     </div>
     </div>
  <div class="col-md-9">
    <div class="row-content">
    		<div class="col-md-10">
    			<div class="row-content">
                <h1 class="list-group-item-heading"><%= @post.title%></h1>
                 <h5><p class="text-justify"><%= @post.body %></p></h5>
            </div>
            	</div>
            
            	<div class="row-content">
                <p class="text-primary"><b> Biography</p></b><br>
            </div>
            	  
               
              </div>
              </div>
</div>


             
            
    </div>


<br>


<%= link_to "Edit Post", edit_post_path(@post),:class=>"btn btn-raised btn-link" %>

<%= link_to "Delete", post_path(@post), :class=>"btn btn-raised btn-danger", method: :delete, data: {confirm: "Are you sure???"} %>








</body>

</html>